name: Deploy on server

on:
  push:
    branches: 
      - master

jobs:
  create-deployment-artifacts:
    name: Create deployment artifacts

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Create deployment artifact

        env:

          GITHUB_SHA: ${{ github.sha }}

        run: tar -czf "${GITHUB_SHA}".tar.gz --exclude=*.git *



      - name: Store artifact for distribution

        uses: actions/upload-artifact@v2

        with:

          name: app-build

          path: ${{ github.sha }}.tar.gz