name: Deploy on server

on:
  push:
    branches: 
      - master

jobs:
  create-deployment-artifacts:
    name: Create deployment artifacts

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

        #- run: echo "Hola mundo"

      - run: |
          git remote add cpanel ssh://amongcod@amongcode.com/home4/amongcod/repositories/deploy
          git push cpanel master

      # - name: Create deployment artifact

      #   env:

      #     GITHUB_SHA: ${{ github.sha }}

      #   run: tar -czf "${GITHUB_SHA}".tar.gz --exclude=*.git *



      # - name: Store artifact for distribution

      #   uses: actions/upload-artifact@v2

      #   with:

      #     name: app-build

      #     path: ${{ github.sha }}.tar.gz
  

  # prepare-release-on-server:

  #   runs-on: ubuntu-latest

  #   needs: create-deployment-artifacts

  #   steps:

  #     - uses: actions/download-artifact@v2

  #       with:

  #         name: app-build
      
  #     - name: Upload

  #       uses: appleboy/scp-action@master

  #       env:

  #         HOST: ${{ secrets.SSH_HOST }}
  #         USERNAME: ${{ secrets.SSH_USERNAME }}
  #         PASSWORD: ${{ secrets.SSH_PWD }}
  #         # PORT: ${{ secrets.SSH_PORT }}

  #       with: 

  #         source: ${{ github.sha }}.tar.gz
  #         target: ~/deploy.amongcode.com
